/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Cls_Productos;

/**
 *
 * @author PC
 */
public class Categorias extends javax.swing.JFrame {
   private final Cls_Productos CP;
    int num = 0;
   
    /**
     * Creates new form Categorias
     */
    public Categorias() {
        initComponents();
        setSize(400, 350);
           CP = new Cls_Productos();
        this.setLocationRelativeTo(null);
    }

    
    
    private void guardar() {
        String id = txtid.getText();
        String cat = txtcategoria.getText();

        //int can = Integer.parseInt(cantidad.getText());

        if (num == 0) {
            int respuesta = CP.insertCat(id,cat);
            if (respuesta > 0) {
             
            }
//        } else {
//            int id = Integer.parseInt(txtid.getText());
//            int respuesta = CP.actualizarCat(id, cat);
//            if (respuesta > 0) {
//             
//                txtid.setText("");
//                num = 0;
//            }
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtcategoria = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        btr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("CATEGORIAS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(116, 25, 158, 29);

        jLabel2.setText("ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 80, 60, 30);

        jLabel3.setText("Nombre de la categoría:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 150, 150, 30);
        getContentPane().add(txtid);
        txtid.setBounds(190, 80, 30, 30);
        getContentPane().add(txtcategoria);
        txtcategoria.setBounds(190, 150, 127, 30);

        guardar.setBackground(new java.awt.Color(0, 0, 0));
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setText("GUARDAR");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        getContentPane().add(guardar);
        guardar.setBounds(240, 230, 110, 40);

        btr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menup.png"))); // NOI18N
        btr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrActionPerformed(evt);
            }
        });
        getContentPane().add(btr);
        btr.setBounds(50, 200, 140, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        guardar();
    }//GEN-LAST:event_guardarActionPerformed

    private void btrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrActionPerformed
        MenuPrincipal e = new MenuPrincipal();
        e.setVisible(true);
        Categorias.this.dispose();
    }//GEN-LAST:event_btrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btr;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtcategoria;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
