package ventanas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author EDWIN
 */
public class Contactos extends javax.swing.JFrame {

    /**
     * Creates new form CONTACTOS
     */
    public Contactos() {
        initComponents();
       ImageIcon imagen = new ImageIcon("src\\interfaz\\fo10.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblfondo.getWidth(), lblfondo.getHeight(), Image.SCALE_DEFAULT));
        lblfondo.setIcon(icono);
        this.repaint();
        ImageIcon imagen4 = new ImageIcon("src\\iconos\\encabezado.png");
        Icon icono4 = new ImageIcon(imagen4.getImage().getScaledInstance(lblcn.getWidth(), lblcn.getHeight(), Image.SCALE_DEFAULT));
        lblcn.setIcon(icono4);
        this.repaint();
        ImageIcon foto2= new ImageIcon("src\\interfaz\\negocio2.jpg");
        Icon icono3 = new ImageIcon(foto2.getImage().getScaledInstance(lblnegocio.getWidth(),lblnegocio.getHeight(),Image.SCALE_DEFAULT));
        lblnegocio.setIcon(icono3);
        this.repaint();
        ImageIcon foto= new ImageIcon("src\\interfaz\\negocio.jpg");
        Icon icono2 = new ImageIcon(foto.getImage().getScaledInstance(lblnegocio2.getWidth(),lblnegocio2.getHeight(),Image.SCALE_DEFAULT));
        lblnegocio2.setIcon(icono2);
        this.repaint();
      
        transparenciaButton();
        setSize(720, 550);
        this.setLocationRelativeTo(null);
    }

    public void transparenciaButton() {

        btr.setOpaque(false);
        btr.setContentAreaFilled(false);
        btr.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btr = new javax.swing.JButton();
        lblnegocio2 = new javax.swing.JLabel();
        lblnegocio = new javax.swing.JLabel();
        lblcn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/contactos.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 20, 180, 70);

        btr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menup.png"))); // NOI18N
        btr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrActionPerformed(evt);
            }
        });
        getContentPane().add(btr);
        btr.setBounds(290, 400, 140, 100);

        lblnegocio2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/negocio.jpg"))); // NOI18N
        getContentPane().add(lblnegocio2);
        lblnegocio2.setBounds(180, 150, 160, 230);

        lblnegocio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/negocio.jpg"))); // NOI18N
        getContentPane().add(lblnegocio);
        lblnegocio.setBounds(10, 60, 160, 230);

        lblcn.setBackground(new java.awt.Color(255, 255, 255));
        lblcn.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        lblcn.setForeground(new java.awt.Color(255, 255, 255));
        lblcn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/encabezado.png"))); // NOI18N
        getContentPane().add(lblcn);
        lblcn.setBounds(370, 80, 320, 140);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("E-mail: mmontes18@gmail.com");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 320, 270, 40);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Propietario: Maria Montes");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(420, 230, 230, 40);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dirección: Av. Fray Vacas Galindo ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(380, 260, 300, 40);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telf.: 0984202291");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(450, 290, 150, 40);

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/fondo.jpg"))); // NOI18N
        getContentPane().add(lblfondo);
        lblfondo.setBounds(0, 0, 710, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrActionPerformed
        MenuPrincipal e = new MenuPrincipal();
        e.setVisible(true);
        Contactos.this.dispose();
    }//GEN-LAST:event_btrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contactos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblcn;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblnegocio;
    private javax.swing.JLabel lblnegocio2;
    // End of variables declaration//GEN-END:variables
}
