/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author PC
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicio1
     */
    public Inicio() {
        initComponents();
        ImageIcon imagen2 = new ImageIcon("src\\iconos\\encabezado.png");
        Icon icono = new ImageIcon(imagen2.getImage().getScaledInstance(lblcn.getWidth(), lblcn.getHeight(), Image.SCALE_DEFAULT));
        lblcn.setIcon(icono);
        this.repaint();
        ImageIcon imagen = new ImageIcon("src\\fondos\\fondo2.jpg");
        Icon icono1 = new ImageIcon(imagen.getImage().getScaledInstance(lblfondo.getWidth(), lblfondo.getHeight(), Image.SCALE_DEFAULT));
        lblfondo.setIcon(icono1);
        this.repaint();
        transparenciaButton();
        setSize(400, 300);
        this.setLocationRelativeTo(null);

    }

    public void transparenciaButton() {

        btr.setOpaque(false);
        btr.setContentAreaFilled(false);
        btr.setBorderPainted(false);
        btis.setOpaque(false);
        btis.setContentAreaFilled(false);
        btis.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btr = new javax.swing.JButton();
        btis = new javax.swing.JButton();
        lblcn = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/inisesion.png"))); // NOI18N
        btr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrActionPerformed(evt);
            }
        });
        getContentPane().add(btr);
        btr.setBounds(20, 160, 160, 60);

        btis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/registro.png"))); // NOI18N
        btis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btisActionPerformed(evt);
            }
        });
        getContentPane().add(btis);
        btis.setBounds(210, 160, 160, 60);

        lblcn.setFont(new java.awt.Font("Comic Sans MS", 0, 70)); // NOI18N
        lblcn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/encabezado.png"))); // NOI18N
        getContentPane().add(lblcn);
        lblcn.setBounds(10, 10, 360, 190);

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/fondo.jpg"))); // NOI18N
        getContentPane().add(lblfondo);
        lblfondo.setBounds(0, 0, 470, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrActionPerformed
        Registro e = new Registro();
        e.setVisible(true);
        Inicio.this.dispose();
    }//GEN-LAST:event_btrActionPerformed

    private void btisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btisActionPerformed
        LogIn e = new LogIn();
        e.setVisible(true);
        Inicio.this.dispose();
    }//GEN-LAST:event_btisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btis;
    private javax.swing.JButton btr;
    private javax.swing.JLabel lblcn;
    private javax.swing.JLabel lblfondo;
    // End of variables declaration//GEN-END:variables
}
