package ventanas;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import clases.Cls_Productos;
import clases.Conectar;

public final class LogIn extends javax.swing.JFrame {
    int timer;
    private final Cls_Productos CP;

    public static String cap;

    public LogIn() {

        initComponents();
         ImageIcon imagen = new ImageIcon("src\\interfaz\\fondo10.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblfondo.getWidth(), lblfondo.getHeight(), Image.SCALE_DEFAULT));
        lblfondo.setIcon(icono);
        this.repaint();
        transparenciaButton();
        CP = new Cls_Productos();
        txtusu.requestFocus();
        setSize(400, 300);
        this.setLocationRelativeTo(null);

    }

    public void transparenciaButton() {

        bts.setOpaque(false);
        bts.setContentAreaFilled(false);
        bts.setBorderPainted(false);
        btr.setOpaque(false);
        btr.setContentAreaFilled(false);
        btr.setBorderPainted(false);
    }

    
      
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")//
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtusu = new javax.swing.JTextField();
        txtpss = new javax.swing.JPasswordField();
        bts = new javax.swing.JButton();
        btr = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inicie Sesión");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 10, 170, 50);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USUARIO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 60, 80, 30);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CONTRASEÑA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 120, 90, 30);

        txtusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuActionPerformed(evt);
            }
        });
        getContentPane().add(txtusu);
        txtusu.setBounds(140, 60, 190, 30);

        txtpss.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpssFocusLost(evt);
            }
        });
        txtpss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpssActionPerformed(evt);
            }
        });
        txtpss.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpssKeyPressed(evt);
            }
        });
        getContentPane().add(txtpss);
        txtpss.setBounds(140, 120, 190, 30);

        bts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/siguiente.png"))); // NOI18N
        bts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsActionPerformed(evt);
            }
        });
        getContentPane().add(bts);
        bts.setBounds(220, 160, 130, 100);

        btr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/regresar.png"))); // NOI18N
        btr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrActionPerformed(evt);
            }
        });
        getContentPane().add(btr);
        btr.setBounds(50, 170, 130, 90);

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/fondo.jpg"))); // NOI18N
        getContentPane().add(lblfondo);
        lblfondo.setBounds(0, -40, 430, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void limpiar(){
        txtusu.setText("");
        txtpss.setText("");
    }
    private void btsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsActionPerformed
          String UsuarioDefecto = "User";
        String PassDefecto = "12345";
        
        
        String U = txtusu.getText();
        String P = txtpss.getText();
        String Tipo = "DefaultProg";
        
        int t = CP.TipoUsuario(U, P);
        if(t==1)
            Tipo = "Administrador";
        else if(t==2)
            Tipo = "Empleado";
        
        if(CP.ValidarUsuario(U,P)>0)
        {
            MenuPrincipal M = new MenuPrincipal();
//            M.userconectado(U,Tipo);
            M.setVisible(true);
            dispose();
            
            if(CP.TipoUsuario(U,P)==2)
                {
                    M.getJMenuBar().getMenu(3).setVisible(false);
                }
        }
        
        else if(U.equals(UsuarioDefecto) && P.equals(PassDefecto)){
            MenuPrincipal M = new MenuPrincipal();
            M.setVisible(true);
            M.getJMenuBar().getMenu(0).setVisible(false);
            M.getJMenuBar().getMenu(1).setVisible(false);
            M.getJMenuBar().getMenu(2).setVisible(false);
            dispose();
//            M.userconectado(U,Tipo);
        }
        else if(timer==3){
        JOptionPane.showMessageDialog(null, "Ha excedido el número máximo de intentos \n Vuelva mas tarde", "ERROR", JOptionPane.ERROR_MESSAGE);
        Inicio e = new Inicio();
        e.setVisible(true);
        LogIn.this.dispose();
        
        }
      else
        {
//            JOptionPane .showMessageDialog(this, );
            JOptionPane.showMessageDialog(this, "Usuario y/o Contraseña incorrecta \n Le resta " +(3-timer)+ " intentos", "ERROR", JOptionPane.WARNING_MESSAGE);
            txtusu.setText("Escriba su nombre de usuario");
            txtpss.setText("");
            timer=  timer + 1;
            limpiar();
        }
    }//GEN-LAST:event_btsActionPerformed

    private void btrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrActionPerformed
        Inicio e = new Inicio();
        e.setVisible(true);
        LogIn.this.dispose();
    }//GEN-LAST:event_btrActionPerformed

    private void txtpssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpssActionPerformed
String UsuarioDefecto = "User";
        String PassDefecto = "12345";
        
        
        String U = txtusu.getText();
        String P = txtpss.getText();
        String Tipo = "DefaultProg";
        
        int t = CP.TipoUsuario(U, P);
        if(t==1)
            Tipo = "Administrador";
        else if(t==2)
            Tipo = "Empleado";
        
        if(CP.ValidarUsuario(U,P)>0)
        {
            MenuPrincipal M = new MenuPrincipal();
//            M.userconectado(U,Tipo);
            M.setVisible(true);
            dispose();
            
            if(CP.TipoUsuario(U,P)==2)
                {
                    M.getJMenuBar().getMenu(3).setVisible(false);
                }
        }
        
        else if(U.equals(UsuarioDefecto) && P.equals(PassDefecto)){
            MenuPrincipal M = new MenuPrincipal();
            M.setVisible(true);
            M.getJMenuBar().getMenu(0).setVisible(false);
            M.getJMenuBar().getMenu(1).setVisible(false);
            M.getJMenuBar().getMenu(2).setVisible(false);
            dispose();
//            M.userconectado(U,Tipo);
        }
        
      else
        {
            JOptionPane.showMessageDialog(this, "Usuario y/o Contraseña incorrecta");
            limpiar();
        }
    }//GEN-LAST:event_txtpssActionPerformed

    private void txtusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuActionPerformed
        // TODO add your handling code here:
        txtusu.requestFocus();

    }//GEN-LAST:event_txtusuActionPerformed

    private void txtpssKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpssKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpssKeyPressed

    private void txtpssFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpssFocusLost


    }//GEN-LAST:event_txtpssFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btr;
    private javax.swing.JButton bts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JPasswordField txtpss;
    private javax.swing.JTextField txtusu;
    // End of variables declaration//GEN-END:variables


}
