/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;


import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import clases.Cls_Productos;
import clases.Conectar;


/**
 *
 * @author PC
 */
public class Registro extends javax.swing.JFrame {
 private final Cls_Productos CP;
    /**
     * Creates new form registro
     */
    public Registro() {
        initComponents();
        ImageIcon imagen = new ImageIcon("src\\interfaz\\fo10.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblfondo.getWidth(), lblfondo.getHeight(), Image.SCALE_DEFAULT));
        lblfondo.setIcon(icono);
        this.repaint();
         CP = new Cls_Productos();
        txtusu.requestFocus();
        setSize(420, 400);
        transparenciaButton();
      
        this.setLocationRelativeTo(null);
    }
    private void limpiar(){
        txtusu.setText("");
        txtpss.setText("");
        txtusu.requestFocus();
    }
    public void transparenciaButton() {

        btreg.setOpaque(false);
        btreg.setContentAreaFilled(false);
        btreg.setBorderPainted(false);
        btr.setOpaque(false);
        btr.setContentAreaFilled(false);
        btr.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtusu = new javax.swing.JTextField();
        btr = new javax.swing.JButton();
        btreg = new javax.swing.JButton();
        txtpss = new javax.swing.JPasswordField();
        boxtipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        idusu = new javax.swing.JTextField();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 153, 0));
        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        jLabel1.setText("REGISTRATE");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 10, 180, 40);

        jLabel2.setBackground(new java.awt.Color(0, 0, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ingresa un nombre de usuario:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 210, 40);

        jLabel3.setBackground(new java.awt.Color(0, 0, 153));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Proporciona una contraseña:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 110, 180, 40);

        txtusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuActionPerformed(evt);
            }
        });
        getContentPane().add(txtusu);
        txtusu.setBounds(120, 90, 210, 30);

        btr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/registrarse.png"))); // NOI18N
        btr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrActionPerformed(evt);
            }
        });
        getContentPane().add(btr);
        btr.setBounds(270, 250, 130, 100);

        btreg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/regresar.png"))); // NOI18N
        btreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btregActionPerformed(evt);
            }
        });
        getContentPane().add(btreg);
        btreg.setBounds(20, 260, 130, 90);

        txtpss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpssActionPerformed(evt);
            }
        });
        getContentPane().add(txtpss);
        txtpss.setBounds(120, 150, 210, 30);

        boxtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Empleado", "Contador" }));
        boxtipo.setSelectedIndex(-1);
        getContentPane().add(boxtipo);
        boxtipo.setBounds(120, 210, 210, 30);

        jLabel4.setBackground(new java.awt.Color(0, 0, 153));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Seleccione el tipo de usuario:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 190, 200, 20);

        idusu.setEditable(false);
        getContentPane().add(idusu);
        idusu.setBounds(350, 30, 6, 20);

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/fondo.jpg"))); // NOI18N
        getContentPane().add(lblfondo);
        lblfondo.setBounds(0, 0, 530, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btregActionPerformed
        Inicio e = new Inicio();
        e.setVisible(true);
        Registro.this.dispose();
    }//GEN-LAST:event_btregActionPerformed

    private void btrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrActionPerformed
      String User = txtusu.getText();
        int v = CP.BuscarUser(User);
        if (v==1){
            JOptionPane.showMessageDialog(null,"Nombre de Usuario Ya Existe.");
            txtusu.setText("");
            txtusu.requestFocus();
        }
        else
            guardar();
Registro.this.dispose();
Inicio e= new Inicio ();
e.setVisible(true);
//        if(){}
//        else{}
    }                                       
    
    private void idUser(){
        int n = CP.idUser();
        n++;
        this.idusu.setText(""+n);
    }
    
    
    private void guardar(){
        //int id1 = Integer.parseInt(idt.getText());
        String u = txtusu.getText();
        String con = txtpss.getText();
        int t1=0;
        
        if(boxtipo.getSelectedIndex()==0){
            t1 = 1;
        }
        if(boxtipo.getSelectedIndex()==1){
            t1=2;
        }
        
        int respuesta = CP.insertDatosUser(u, con, t1);
        if(respuesta >0){
           
            limpiar();
         }      
    
    
    }//GEN-LAST:event_btrActionPerformed

    
    private void txtpssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpssActionPerformed

    private void txtusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxtipo;
    private javax.swing.JButton btr;
    private javax.swing.JButton btreg;
    private javax.swing.JTextField idusu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JPasswordField txtpss;
    private javax.swing.JTextField txtusu;
    // End of variables declaration//GEN-END:variables
}
