/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.JOptionPane;
import clases.Cls_Productos;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Dell
 */
public class RegProveedores extends javax.swing.JFrame {

    static String Ci;
    static String Nombre;
    static String Gerente;
    static String Direccion;
    static String Mail;
    static String Telf;
    static int cont = 0;
    private final Cls_Productos CP;
    int num = 0;
    /**
     * Creates new form RegClientes
     */
    public RegProveedores() {
        initComponents();
        ImageIcon imagen = new ImageIcon("src\\fondos\\fondo3.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblfondo.getWidth(), lblfondo.getHeight(), Image.SCALE_DEFAULT));
        lblfondo.setIcon(icono);
        this.repaint();
        setSize(849, 711);
        this.setLocationRelativeTo(null);
//        CTID.setVisible(false);
//        CTID.setEnabled(false);

        CP = new Cls_Productos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CTIDENTIDAD = new javax.swing.JTextField();
        CTNOMBRE = new javax.swing.JTextField();
        CTDIRECCION = new javax.swing.JTextField();
        CTEMAIL = new javax.swing.JTextField();
        CTGERENTE = new javax.swing.JTextField();
        CTID = new javax.swing.JTextField();
        CTTELEFONO = new javax.swing.JTextField();
        btnregresar = new javax.swing.JButton();
        jb_nuevo = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        BTNBUSCAR = new javax.swing.JButton();
        btnagregar = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Registro de Proveedor");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 20, 330, 33);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 87, 25, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("NOMBRE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 200, 63, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("DIRECCIÓN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 260, 100, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("GERENTE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 320, 67, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("TELÉFONO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(150, 380, 76, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("E-MAIL");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(150, 430, 52, 17);

        CTIDENTIDAD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CTIDENTIDADFocusLost(evt);
            }
        });
        CTIDENTIDAD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CTIDENTIDADKeyTyped(evt);
            }
        });
        getContentPane().add(CTIDENTIDAD);
        CTIDENTIDAD.setBounds(400, 140, 200, 30);

        CTNOMBRE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CTNOMBREKeyTyped(evt);
            }
        });
        getContentPane().add(CTNOMBRE);
        CTNOMBRE.setBounds(400, 200, 200, 30);

        CTDIRECCION.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CTDIRECCIONKeyTyped(evt);
            }
        });
        getContentPane().add(CTDIRECCION);
        CTDIRECCION.setBounds(400, 260, 200, 30);

        CTEMAIL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CTEMAILFocusLost(evt);
            }
        });
        getContentPane().add(CTEMAIL);
        CTEMAIL.setBounds(400, 430, 200, 30);
        getContentPane().add(CTGERENTE);
        CTGERENTE.setBounds(400, 320, 200, 30);
        getContentPane().add(CTID);
        CTID.setBounds(400, 90, 120, 30);

        CTTELEFONO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CTTELEFONOKeyTyped(evt);
            }
        });
        getContentPane().add(CTTELEFONO);
        CTTELEFONO.setBounds(400, 380, 200, 30);

        btnregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/regresar.png"))); // NOI18N
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnregresar);
        btnregresar.setBounds(350, 490, 130, 80);

        jb_nuevo.setBackground(new java.awt.Color(0, 0, 0));
        jb_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        jb_nuevo.setText("NUEVO");
        jb_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_nuevoActionPerformed(evt);
            }
        });
        getContentPane().add(jb_nuevo);
        jb_nuevo.setBounds(660, 330, 90, 40);

        guardar.setBackground(new java.awt.Color(0, 0, 0));
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setText("GUARDAR");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        getContentPane().add(guardar);
        guardar.setBounds(660, 270, 90, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("C.I.");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(150, 150, 25, 17);

        BTNBUSCAR.setBackground(new java.awt.Color(0, 0, 0));
        BTNBUSCAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTNBUSCAR.setForeground(new java.awt.Color(51, 255, 51));
        BTNBUSCAR.setText("BUSCAR");
        BTNBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBUSCARActionPerformed(evt);
            }
        });
        getContentPane().add(BTNBUSCAR);
        BTNBUSCAR.setBounds(660, 120, 90, 60);

        btnagregar.setBackground(new java.awt.Color(0, 0, 0));
        btnagregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnagregar.setForeground(new java.awt.Color(51, 255, 51));
        btnagregar.setText("AGREGAR");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnagregar);
        btnagregar.setBounds(660, 200, 90, 50);

        lblfondo.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        getContentPane().add(lblfondo);
        lblfondo.setBounds(0, 0, 850, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void guardar() {
//        String id=CTID.getText();
        String nom = CTNOMBRE.getText();
        String ci = CTIDENTIDAD.getText();
        String dir = CTDIRECCION.getText();
        String mail = CTEMAIL.getText();
        String ger = CTGERENTE.getText();
        String tel = CTTELEFONO.getText();
        if (num == 0) {
            int respuesta = CP.insertDatosProveedor(ci, nom, dir, ger, tel, mail);
            if (respuesta > 0) {

                limpiar();
            }
        } else {
            int RUC = Integer.parseInt(CTIDENTIDAD.getText());
            int respuesta = CP.actualizarProveedor(ci, nom, dir, tel, mail, ger);
            if (respuesta > 0) {
                limpiar();
                CTIDENTIDAD.setText("");
                num = 0;

           
            }
    }
    }
    private void limpiar() {
        //codigo.setText("");
        CTNOMBRE.setText("");
        CTIDENTIDAD.setText("");
        CTDIRECCION.setText("");
        CTTELEFONO.setText("");
        CTEMAIL.setText("");
        CTGERENTE.setText("");

        //cantidad.setText("");
        CTNOMBRE.requestFocus();
    }


    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        MenuPrincipal e = new MenuPrincipal();
        e.setVisible(true);
        RegProveedores.this.dispose();

    }//GEN-LAST:event_btnregresarActionPerformed

    private void CTIDENTIDADKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CTIDENTIDADKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_CTIDENTIDADKeyTyped

    private void CTNOMBREKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CTNOMBREKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isDigit(validar)) {
            getToolkit().beep();

            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Ingresar solo letras");
        }

        if (Character.isLowerCase(validar)) {
            String cad = ("" + validar).toUpperCase();
            validar = cad.charAt(0);
            evt.setKeyChar(validar);
        }
        if ((validar < 'a' || validar > 'z') && (validar < 'A') | validar > 'Z' && (validar != ' ')) {
            evt.consume();
        }
    }//GEN-LAST:event_CTNOMBREKeyTyped

    private void CTDIRECCIONKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CTDIRECCIONKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isDigit(validar)) {
            getToolkit().beep();

            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Ingresar solo letras");
        }

        if (Character.isLowerCase(validar)) {
            String cad = ("" + validar).toUpperCase();
            validar = cad.charAt(0);
            evt.setKeyChar(validar);
        }
        if ((validar < 'a' || validar > 'z') && (validar < 'A') | validar > 'Z' && (validar != ' ')) {
            evt.consume();
        }
    }//GEN-LAST:event_CTDIRECCIONKeyTyped

    private void CTTELEFONOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CTTELEFONOKeyTyped
//        char c = evt.getKeyChar();
//        if (c < '0' || c > '9') {
//            evt.consume();
//        }
    }//GEN-LAST:event_CTTELEFONOKeyTyped

    private void CTIDENTIDADFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CTIDENTIDADFocusLost
        int tam = CTIDENTIDAD.getText().length();
        int pos = 0;
        int dig = 0;
        String ced = CTIDENTIDAD.getText();
        int acum = 0;
        if (tam == 10) {
            while (pos < tam) {
                dig = Integer.parseInt(ced.substring(pos, pos + 1));
                if ((pos + 1) % 2 != 0) {
                    dig = dig * 2;
                    if (dig > 9) {
                        dig = dig - 9;
                    }
                    acum = acum + dig;
                } else {
                    acum = acum + dig;
                }
                pos++;
            }
            if (acum % 10 == 0) {
                JOptionPane.showMessageDialog(null, "Cédula Válida", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                //btok.setIcon(new ImageIcon("\\imgs\\ok.jpeg"));
                CTNOMBRE.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Cédula Ecuatoriana no Válida", "Advertencia", JOptionPane.ERROR_MESSAGE);
                //btok.setIcon(new ImageIcon("\\imgs\\nok.jpeg"));
                CTIDENTIDAD.requestFocus();
                CTIDENTIDAD.selectAll();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Cédula Ecuatoriana no Válida", "Advertencia", JOptionPane.ERROR_MESSAGE);
            //btok.setIcon(new ImageIcon("src\\apptienda\\img\\iconoerror.png"));
            CTIDENTIDAD.requestFocus();
            CTIDENTIDAD.selectAll();
        }


    }//GEN-LAST:event_CTIDENTIDADFocusLost

    private void CTEMAILFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CTEMAILFocusLost
        Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");

        // El email a validar
        String email = CTEMAIL.getText();

        Matcher mather = pattern.matcher(email);

        if (mather.find() == true) {

            JOptionPane.showMessageDialog(null, "Email intriducido válido", "Excelente", JOptionPane.INFORMATION_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(null, "Email introducido inválido", "Error", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_CTEMAILFocusLost

    private void jb_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_nuevoActionPerformed
        CTID.setText("");
        limpiar();

    }//GEN-LAST:event_jb_nuevoActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        guardar();// METODO
    }//GEN-LAST:event_guardarActionPerformed

    private void BTNBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBUSCARActionPerformed
        BuscarProveedor buscacli = new BuscarProveedor();
        buscacli.show();
    }//GEN-LAST:event_BTNBUSCARActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed

        this.CTNOMBRE.setText(this.Nombre);
        this.CTIDENTIDAD.setText(Ci);
        this.CTDIRECCION.setText(Direccion);
        this.CTEMAIL.setText(Mail);
        this.CTGERENTE.setText(Gerente);
        this.CTTELEFONO.setText(Telf);
    }//GEN-LAST:event_btnagregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegProveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBUSCAR;
    private javax.swing.JTextField CTDIRECCION;
    private javax.swing.JTextField CTEMAIL;
    private javax.swing.JTextField CTGERENTE;
    private javax.swing.JTextField CTID;
    private javax.swing.JTextField CTIDENTIDAD;
    private javax.swing.JTextField CTNOMBRE;
    private javax.swing.JTextField CTTELEFONO;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnregresar;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jb_nuevo;
    private javax.swing.JLabel lblfondo;
    // End of variables declaration//GEN-END:variables
}
