/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

import clases.reportes;

/**
 *
 * @author PC
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form REPORTES
     */
    public Reportes() {
        initComponents();
        setSize(430, 360);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btclientes = new javax.swing.JButton();
        btempleados = new javax.swing.JButton();
        btproductos = new javax.swing.JButton();
        btproveedores = new javax.swing.JButton();
        btadquisiciones = new javax.swing.JButton();
        btventas = new javax.swing.JButton();
        btr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("REPORTES");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 20, 240, 33);

        btclientes.setText("CLIENTES");
        btclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btclientesActionPerformed(evt);
            }
        });
        getContentPane().add(btclientes);
        btclientes.setBounds(20, 60, 110, 60);

        btempleados.setText("EMPLEADOS");
        btempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btempleadosActionPerformed(evt);
            }
        });
        getContentPane().add(btempleados);
        btempleados.setBounds(20, 140, 110, 60);

        btproductos.setText("PRODUCTOS");
        btproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btproductosActionPerformed(evt);
            }
        });
        getContentPane().add(btproductos);
        btproductos.setBounds(280, 60, 120, 60);

        btproveedores.setText("PROVEEDORES");
        btproveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btproveedoresActionPerformed(evt);
            }
        });
        getContentPane().add(btproveedores);
        btproveedores.setBounds(140, 60, 130, 60);

        btadquisiciones.setText("ADQUISICIONES");
        btadquisiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btadquisicionesActionPerformed(evt);
            }
        });
        getContentPane().add(btadquisiciones);
        btadquisiciones.setBounds(140, 140, 130, 60);

        btventas.setText("VENTAS");
        btventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btventasActionPerformed(evt);
            }
        });
        getContentPane().add(btventas);
        btventas.setBounds(280, 140, 120, 60);

        btr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menuprincipal.png"))); // NOI18N
        btr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrActionPerformed(evt);
            }
        });
        getContentPane().add(btr);
        btr.setBounds(130, 210, 140, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btclientesActionPerformed
        reportes conn = new reportes();
        Connection con = reportes.getConexion();

        JasperReport reporte = null;
        String path = "src\\reportes\\reportecliente.jasper";

        try {
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);

            JasperPrint jprint = JasperFillManager.fillReport(path, null, con);
            JasperViewer view = new JasperViewer(jprint, false);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btclientesActionPerformed

    private void btproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btproductosActionPerformed
        reportes conn = new reportes();
        Connection con = reportes.getConexion();

        JasperReport reporte = null;
        String path = "src\\reportes\\reporteproductos.jasper";

        try {
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);

            JasperPrint jprint = JasperFillManager.fillReport(path, null, con);
            JasperViewer view = new JasperViewer(jprint, false);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btproductosActionPerformed

    private void btadquisicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btadquisicionesActionPerformed
        reportes conn = new reportes();
        Connection con = reportes.getConexion();

        JasperReport reporte = null;
        String path = "src\\reportes\\reporteadquisiciones.jasper";

        try {
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);

            JasperPrint jprint = JasperFillManager.fillReport(path, null, con);
            JasperViewer view = new JasperViewer(jprint, false);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btadquisicionesActionPerformed

    private void btventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btventasActionPerformed
        reportes conn = new reportes();
        Connection con = reportes.getConexion();

        JasperReport reporte = null;
        String path = "src\\reportes\\reporteventas.jasper";

        try {
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);

            JasperPrint jprint = JasperFillManager.fillReport(path, null, con);
            JasperViewer view = new JasperViewer(jprint, false);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btventasActionPerformed

    private void btempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btempleadosActionPerformed
        reportes conn = new reportes();
        Connection con = reportes.getConexion();

        JasperReport reporte = null;
        String path = "src\\reportes\\reporteempleados.jasper";

        try {
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);

            JasperPrint jprint = JasperFillManager.fillReport(path, null, con);
            JasperViewer view = new JasperViewer(jprint, false);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btempleadosActionPerformed

    private void btproveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btproveedoresActionPerformed
        reportes conn = new reportes();
        Connection con = reportes.getConexion();

        JasperReport reporte = null;
        String path = "src\\reportes\\reporteproveedores.jasper";

        try {
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);

            JasperPrint jprint = JasperFillManager.fillReport(path, null, con);
            JasperViewer view = new JasperViewer(jprint, false);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btproveedoresActionPerformed

    private void btrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrActionPerformed
        MenuPrincipal e = new MenuPrincipal();
        e.setVisible(true);
        Reportes.this.dispose();
    }//GEN-LAST:event_btrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadquisiciones;
    private javax.swing.JButton btclientes;
    private javax.swing.JButton btempleados;
    private javax.swing.JButton btproductos;
    private javax.swing.JButton btproveedores;
    private javax.swing.JButton btr;
    private javax.swing.JButton btventas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
