/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import ventanas.BuscarClientes;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.DecimalFormat;
import java.text.MessageFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import clases.Cls_Productos;

/**
 *
 * @author PC
 */
public class Venta extends javax.swing.JFrame implements Printable {

    Calendar fechactual = new GregorianCalendar();
    float t1, t2, t3 = 0;
    double iva;
    double descuento;
    private final Cls_Productos CP;
    DecimalFormat formato1 = new DecimalFormat("#.00");
    int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
    int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;

    //Estas variables staticas son especiales si es que kiero pasarlas a otro jframe
    //instanciando la clase frm_Facturacion puedo acceder a estas e igualarlas luego
    static String Codigo;
    static String NombreCompleto;
    static String Ruc;
    static int cont = 0; //Contador para el mensaje, "Solo aparesca una vez"
    String numerofactura;
    float valor = 0;
    Cls_Productos factu = new Cls_Productos();

    DefaultTableModel dtm = new DefaultTableModel();

    /**
     * Creates new form frm_Facturacion
     */
    /**
     * Creates new form Venta
     */
    public Venta() {
        initComponents();

        ImageIcon imagen1 = new ImageIcon("src\\iconos\\encabezado.png");
        Icon icono3 = new ImageIcon(imagen1.getImage().getScaledInstance(lblcn.getWidth(), lblcn.getHeight(), Image.SCALE_DEFAULT));
        lblcn.setIcon(icono3);
        ImageIcon imagen2 = new ImageIcon("src\\interfaz\\fo10.jpg");
        Icon icono = new ImageIcon(imagen2.getImage().getScaledInstance(lblfondo1.getWidth(), lblfondo1.getHeight(), Image.SCALE_DEFAULT));
        lblfondo1.setIcon(icono);
        this.repaint();
        ImageIcon imagen = new ImageIcon("src\\interfaz\\fondoblanco.jpg");
        Icon icono1 = new ImageIcon(imagen.getImage().getScaledInstance(lblfondo.getWidth(), lblfondo.getHeight(), Image.SCALE_DEFAULT));
        lblfondo.setIcon(icono1);
        this.repaint();
        btnagregar.setEnabled(false);
        btngrabar.setEnabled(false);
        CP = new Cls_Productos();
        dtm.addColumn("Cantidad");
        dtm.addColumn("Descripción");
        dtm.addColumn("Precio Unitario");
        dtm.addColumn("Valor Total");
        this.jTable1.setModel(dtm);
        this.setSize(1245, 650);
        this.setLocationRelativeTo(null);
        btngrabar.setText("<html><p>Realizar</p><p>venta</p></html>");

        factu();
        jtf_fecha.setCalendar(fechactual);
    }

    private void limpiar() {
        jtf_id1.setText("");
        jtf_nombres.setText("");
        jtf_tel.setText("");
        jtf_fecha.setDate(null);
        txtsubtotal.setText("");
        txtigv.setText("");
        txttotal.setText("");

        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        factu();
    }

    private void factu() {
        int n = CP.factu();
        n++;
        this.txtnumerodefac.setText("000" + n);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jtf_id1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtf_nombres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtf_tel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtf_fecha = new com.toedter.calendar.JDateChooser();
        btngrabar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtsubtotal = new javax.swing.JTextField();
        txtigv = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableProducto = new javax.swing.JTable();
        txtnumerodefac = new javax.swing.JTextField();
        btnbuscarproduc = new javax.swing.JButton();
        btnbuscarcli = new javax.swing.JButton();
        btnagregar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblcn = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        lblfondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("RUC/CI:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 170, 44, 30);

        jtf_id1.setEditable(false);
        jtf_id1.setBackground(new java.awt.Color(255, 255, 255));
        jtf_id1.setBorder(null);
        getContentPane().add(jtf_id1);
        jtf_id1.setBounds(110, 170, 190, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Cliente:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 200, 42, 30);

        jtf_nombres.setEditable(false);
        jtf_nombres.setBackground(new java.awt.Color(255, 255, 255));
        jtf_nombres.setBorder(null);
        getContentPane().add(jtf_nombres);
        jtf_nombres.setBounds(110, 200, 190, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Teléfono:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 230, 52, 30);

        jtf_tel.setEditable(false);
        jtf_tel.setBackground(new java.awt.Color(255, 255, 255));
        jtf_tel.setBorder(null);
        getContentPane().add(jtf_tel);
        jtf_tel.setBounds(110, 230, 130, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Fecha:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 250, 60, 50);

        jtf_fecha.setDateFormatString("yyyy/MM/dd");
        jtf_fecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtf_fechaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtf_fechaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtf_fechaMouseReleased(evt);
            }
        });
        getContentPane().add(jtf_fecha);
        jtf_fecha.setBounds(90, 260, 150, 30);

        btngrabar.setBackground(new java.awt.Color(0, 0, 0));
        btngrabar.setForeground(new java.awt.Color(255, 255, 255));
        btngrabar.setText("Grabar");
        btngrabar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });
        getContentPane().add(btngrabar);
        btngrabar.setBounds(620, 370, 90, 40);

        btnnuevo.setBackground(new java.awt.Color(0, 0, 0));
        btnnuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnnuevo);
        btnnuevo.setBounds(620, 310, 90, 40);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(620, 430, 90, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTable1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 300, 530, 170);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("IVA 12%     $");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Sub Total    $");

        txtsubtotal.setEditable(false);
        txtsubtotal.setBackground(new java.awt.Color(255, 255, 255));
        txtsubtotal.setBorder(null);

        txtigv.setEditable(false);
        txtigv.setBackground(new java.awt.Color(255, 255, 255));
        txtigv.setBorder(null);
        txtigv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtigvActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Total            $");
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txttotal.setEditable(false);
        txttotal.setBackground(new java.awt.Color(255, 255, 255));
        txttotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtigv)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtigv, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(380, 480, 160, 110);

        tableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProductoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableProducto);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(750, 170, 450, 200);

        txtnumerodefac.setEditable(false);
        txtnumerodefac.setBackground(new java.awt.Color(255, 255, 255));
        txtnumerodefac.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtnumerodefac.setBorder(null);
        txtnumerodefac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumerodefacActionPerformed(evt);
            }
        });
        getContentPane().add(txtnumerodefac);
        txtnumerodefac.setBounds(450, 10, 90, 30);

        btnbuscarproduc.setBackground(new java.awt.Color(0, 0, 0));
        btnbuscarproduc.setForeground(new java.awt.Color(255, 255, 255));
        btnbuscarproduc.setText("Productos");
        btnbuscarproduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarproducActionPerformed(evt);
            }
        });
        getContentPane().add(btnbuscarproduc);
        btnbuscarproduc.setBounds(910, 100, 120, 40);

        btnbuscarcli.setBackground(new java.awt.Color(0, 0, 0));
        btnbuscarcli.setForeground(new java.awt.Color(255, 255, 255));
        btnbuscarcli.setText("Buscar Clientes");
        btnbuscarcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarcliActionPerformed(evt);
            }
        });
        getContentPane().add(btnbuscarcli);
        btnbuscarcli.setBounds(600, 80, 130, 40);

        btnagregar.setBackground(new java.awt.Color(0, 0, 0));
        btnagregar.setForeground(new java.awt.Color(255, 255, 255));
        btnagregar.setText("Añadir");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnagregar);
        btnagregar.setBounds(620, 140, 90, 40);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Nuevo Cliente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(600, 20, 130, 40);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Factura N°:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 10, 80, 30);

        lblcn.setFont(new java.awt.Font("Comic Sans MS", 0, 70)); // NOI18N
        lblcn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cuidadonatural.png"))); // NOI18N
        getContentPane().add(lblcn);
        lblcn.setBounds(170, 30, 220, 100);

        jLabel5.setText("AV. FRAY VACAS GALINDO, MERCADO LA PLAYITA");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 150, 300, 20);

        jLabel8.setText("MONTE SACA MARIA GRISELDA");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(200, 110, 200, 20);

        jLabel11.setText("1802382430");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(240, 130, 70, 20);

        jLabel12.setText("____________________");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(230, 550, 140, 14);

        jLabel13.setText("Recibí Conforme");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(70, 570, 120, 30);

        jLabel15.setText("Entregué Conforme");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(250, 570, 110, 30);

        jLabel14.setText("____________________");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(50, 550, 140, 14);

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/fondoblanco.jpg"))); // NOI18N
        lblfondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(lblfondo);
        lblfondo.setBounds(0, 0, 570, 610);

        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/regresar.png"))); // NOI18N
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar);
        cancelar.setBounds(900, 480, 120, 100);

        lblfondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/fondo5.jpg"))); // NOI18N
        getContentPane().add(lblfondo1);
        lblfondo1.setBounds(580, 0, 650, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed
        factu.buscarproducto(this.tableProducto);
        int cantidad_saldo;
        float total_saldo;
        String ced = jtf_id1.getText();
        String fecha = ((JTextField) jtf_fecha.getDateEditor().getUiComponent()).getText();
        float pre;
        pre = (float) (0.12 * t3) + t3;
        int respuesta = CP.insertDatosFac(ced, fecha, pre);
        if (respuesta > 0) {
            JOptionPane.showMessageDialog(null, "Factura Guardada con Éxito");
        }

        int n2 = CP.factu();

        for (int i = 0; i < dtm.getRowCount(); i++) {
            String prod = jTable1.getValueAt(i, 1).toString();
            int can = Integer.parseInt(jTable1.getValueAt(i, 0).toString());

            int codpro = CP.CodPro(prod);
            float vu = CP.ValorProd(codpro) * can;

            CP.insertDatosInvSalidas(codpro, can);
            CP.updateSalidas(codpro, can, n2, fecha, vu);
            factu.buscarproducto(this.tableProducto);

            int registros = CP.totalRegistros();
            if (registros > 0) {
                System.out.println("Datos por que si existen registros!");
                cantidad_saldo = CP.cantidadSaldo(codpro);
                total_saldo = CP.totalSaldo(codpro);
                cantidad_saldo -= can;
                total_saldo += vu;
            } else {
                cantidad_saldo = 0;
                total_saldo = 0;
                cantidad_saldo -= can;
                total_saldo -= vu;
                System.out.println("Valor total de entrada: " + total_saldo);
            }

            CP.insertDatosKardexSalidas(fecha, "Venta", codpro, can, vu, cantidad_saldo, total_saldo);
        }

    }//GEN-LAST:event_btngrabarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed

        limpiar();

    }//GEN-LAST:event_btnnuevoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        printerJob.setPrintable(this);
        if (printerJob.printDialog()) {
            try {
                printerJob.print();
            } catch (PrinterException ex) {
                System.out.println("Error" + ex);

            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyTyped

    private void txtigvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtigvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtigvActionPerformed

    private void tableProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProductoMouseClicked
        // TODO add your handling code here:
        float temp;
        float iva = 1.12f;
        float t;
        String ban = (JOptionPane.showInputDialog(null, "Ingrese Cantidad", "Mensaje", WIDTH));
        //pasamos al jtable la cantidad que ingrese en el textbox
        int ban2 = Integer.parseInt(ban);
        //System.out.println(ban);

        if (ban != null) {
            int cod = Integer.parseInt(this.tableProducto.getValueAt(this.tableProducto.getSelectedRow(), 0).toString());
            int stock = CP.busquedap(cod);

            if (ban2 >= stock) {
                JOptionPane.showMessageDialog(null, "Stock Insuficiente");
            } else {
                //int cod = Integer.parseInt(this.tableProducto.getValueAt(this.tableProducto.getSelectedRow(), 0).toString());
                temp = Float.parseFloat(this.tableProducto.getValueAt(this.tableProducto.getSelectedRow(), 2).toString()); //Extrae Precio Unitario
                temp = temp / iva;
                t1 = temp;

                Object vector[] = new Object[4];
                vector[0] = "";
                vector[1] = this.tableProducto.getValueAt(this.tableProducto.getSelectedRow(), 1); //Descripcion
                vector[2] = formato1.format(temp);                                              //P Unitario
                vector[3] = "";
                dtm.addRow(vector);

                this.jTable1.setValueAt(ban2, this.jTable1.getRowCount() - 1, 0);  //CANTIDAD
                //this.jTable1.setValueAt((ban2*temp),this.jTable1.getRowCount()-1,3);
                t = temp * ban2;
                t2 = t1 * ban2;

                this.jTable1.setValueAt(formato1.format(t), this.jTable1.getRowCount() - 1, 3); //Muestra en tabla columna 4(v total)

                valor = valor + t;
                t3 = t3 + t2;

                this.txtsubtotal.setText("" + formato1.format(valor));
                this.txtigv.setText("" + formato1.format(valor * 0.12));

                double total = (valor * 0.12) + valor;
                this.txttotal.setText("" + formato1.format(total));

                //String fecha = ((JTextField)jtf_fecha.getDateEditor().getUiComponent()).getText();
                //int n2 = CP.factu();
                //CP.updateSalidas(cod, ban2,n2,fecha);
                factu.buscarproducto(this.tableProducto);
            }

        }

    }//GEN-LAST:event_tableProductoMouseClicked

    private void txtnumerodefacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumerodefacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumerodefacActionPerformed

    private void btnbuscarproducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarproducActionPerformed
        String fecha = ((JTextField) jtf_fecha.getDateEditor().getUiComponent()).getText();
        int tam = fecha.length();

        if (tam < 5) {
            JOptionPane.showMessageDialog(null, "Primero Ingresar Datos del Cliente y Fecha");
        } else {
            btngrabar.setEnabled(true);
            factu.buscarproducto(this.tableProducto);

        }

    }//GEN-LAST:event_btnbuscarproducActionPerformed

    private void btnbuscarcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarcliActionPerformed
        // TODO add your handling code here:
        BuscarClientes buscacli = new BuscarClientes();
        buscacli.show();
        this.btnagregar.setEnabled(true);
    }//GEN-LAST:event_btnbuscarcliActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        // TODO add your handling code here:
        this.jtf_id1.setText(this.Codigo);
        this.jtf_nombres.setText(this.NombreCompleto);
        this.jtf_tel.setText(Ruc);
    }//GEN-LAST:event_btnagregarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        RegClientesVenta e = new RegClientesVenta();
        e.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtf_fechaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtf_fechaMouseReleased

    }//GEN-LAST:event_jtf_fechaMouseReleased

    private void jtf_fechaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtf_fechaMousePressed
        btnbuscarproduc.setEnabled(true);
    }//GEN-LAST:event_jtf_fechaMousePressed

    private void jtf_fechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtf_fechaMouseClicked

    }//GEN-LAST:event_jtf_fechaMouseClicked

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        MenuPrincipal e = new MenuPrincipal();
        e.setVisible(true);
        Venta.this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venta().setVisible(true);
            }
        });
    }

    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        if (pageIndex == 0) {
            Graphics2D graphics2d = (Graphics2D) graphics;
            graphics2d.translate(pageFormat.getImageableX() + 10, pageFormat.getImageableY() + 20);
            print(graphics2d);
            return PAGE_EXISTS;
        } else {
            return NO_SUCH_PAGE;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnbuscarcli;
    private javax.swing.JButton btnbuscarproduc;
    private javax.swing.JButton btngrabar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser jtf_fecha;
    private javax.swing.JTextField jtf_id1;
    private javax.swing.JTextField jtf_nombres;
    private javax.swing.JTextField jtf_tel;
    private javax.swing.JLabel lblcn;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblfondo1;
    private javax.swing.JTable tableProducto;
    private javax.swing.JTextField txtigv;
    private javax.swing.JTextField txtnumerodefac;
    private javax.swing.JTextField txtsubtotal;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
